---
- name: Check or create Minio Docker Compose directory
  file:
    path: "{{ minio_path }}"
    state: directory
    mode: '0755'

- name: Deploy Minio Docker Compose configuration
  template:
    src: docker-compose.yml.j2
    dest: "{{ minio_path }}/docker-compose.yml"
  notify: Start Minio cluster

- name: Ensure Minio cluster is running
  community.docker.docker_compose_v2:
    project_src: "{{ minio_path}}"
    state: present
