---
- name: Check or create Minio Docker Compose directory
  ansible.builtin.file:
    path: "{{ minio_path }}"
    state: directory
    mode: '0755'

- name: Install pip3
  ansible.builtin.apt:
    name: python3-pip
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Ensure Docker SDK and Docker Compose for Python is installed
  ansible.builtin.pip:
    name:
      - "docker==6.1.3"
      - "docker-compose"
    state: present

- name: Deploy Minio Docker Compose configuration
  template:
    src: docker-compose.yml.j2
    dest: "{{ minio_path }}/docker-compose.yml"
  notify: Start Minio cluster

- name: Ensure Minio cluster is running
  docker_compose:
    project_src: "{{ minio_path }}"
    pull: yes
    restarted: yes
