---
- name: Check or create Minio Docker Compose directory
  file:
    path: "{{ minio_path }}"
    state: directory
    mode: '0755'

- name: Deploy Minio configurations
  template:
    src: "{{ item.src }}"
    dest: "{{ minio_path }}/{{ item.dest }}"
  with_items:
    - { src: 'docker-compose.yml.j2', dest: 'docker-compose.yml' }
    - { src: 'caddyfile-minio.j2', dest: 'Caddyfile' }
  notify: Start Minio cluster

- name: Ensure Minio is running
  community.docker.docker_compose_v2:
    project_src: "{{ minio_path}}"
    state: present
