---
- block:  # Block for Debian OS family
  - name: Update APT package cache
    apt:
      update_cache: yes

  - name: Install prerequisites APT packages
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: present

  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 0EBFCD88
      state: present

  - name: Add Docker APT repository
    apt_repository:
      repo: "deb [arch={{ ansible_architecture | replace('x86_64', 'amd64') | replace('aarch64', 'arm64') }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
      state: present

  - name: Install Docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present
      update_cache: yes

  when: 
    - ansible_os_family == 'Debian'
    - docker_installed is false
