---
- name: Check if Docker is installed
  command: docker --version             # Run the command to check if Docker is installed
  register: docker_check                # Register the output of the command to the variable docker_check
  ignore_errors: true                   # Ignore errors and continue with the next task
  changed_when: false                   # Do not mark the task as changed

# Set the fact docker_installed to true if the command was successful
- set_fact:
    docker_installed: true                
  when: docker_check is not failed      

# Set the fact docker_installed to false if the command failed
- set_fact:
    docker_installed: false               
  when: docker_check is failed
